### ISSUE TITLE
Impossible:  process count too high.  Bug bug

### ISSUE THREAD

**Issue by Shelvak** [dave-andersen/fastrie#9]
Hi there, I'm trying to get the miner working on ubuntu and I can't (It works on arch linux... so the bin file works)

I downloaded the client from http://riepool.ovh/downloads/New_Linux64_xptminer.zip 
I tried in a few servers and I can't get that working.

I'll paste the log
```
 ~ ./xptminer2 -u account.worker1 -p 1234 -t 4                                                                                                       
-----------------------------------------
  xptMiner/ric/dga/Simba84 (xptMiner 2.2)
  author: jh00 (xptminer originally for http://ypool.net)
          dga/Simba84 (ric core)
-----------------------------------------
Launching miner...

Using 4 +1 CPU threads
Launching the 5 threads

Connected to server using 'account.worker1' username...
session id (null)
extraNonce1 4 ff8402f8
extraNonce2Len 4

Generating table of small primes for Riecoin...
[00:00:00] Start mining
[00:00:00] 2ch/s: 0.0000 3ch/s: 0.0000 4ch/s: 0.0000 Shares total: 0 / 0
Impossible:  process count too high.  Bug bug
```

One of the servers has:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
Kernel => 3.19.0-58-generic #64~14.04.1-Ubuntu SMP Fri Mar 18 19:05:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Proc: i3 530  @ 2.93GHz
Ram 16Gb

And I have the 4 free procs  and at least 12Gb of free ram...

I have no idea what I can do (more than increase the number here: https://github.com/dave-andersen/fastrie/blob/master/xptMiner/xptMiner/riecoinMiner.cpp#L806  =P  )

Thanks in advance.

**Comment by williamccrobinson** [comment]
I ran into the same issue on Debian Jessie using the same binary you downloaded. The odd part is I had used this binary on my other Debian Jessie machine that I set up before the non-functioning one, and it worked. 

Turns out I was missing some dependencies on the non-functioning machine. I went back to the [riepool getting started section](http://riepool.ovh/index.php?page=gettingstarted) and noticed that I hadn't followed Section 3, in which it instructs to run (from your working directory of choice)
`sudo apt-get install build-essential m4 openssl libssl-dev git libjson0 libjson0-dev libcurl4-openssl-dev wget libjansson-dev

wget http://mirrors.kernel.org/gnu/gmp/gmp-6.0.0a.tar.bz2 
tar xjvf gmp-6.0.0a.tar.bz2 
cd gmp-6.0.0 
./configure --enable-cxx 
make -j4 && sudo make install 
cd ..
git clone https://github.com/gatra/fastrie.git 
cd fastrie/xptMiner 
LD_LIBRARY_PATH=/usr/local/lib make -j4 `

After doing so, everything was working fine! I hope this works for you too. 

Cheers   （ ^_^）o自自o（^_^ ）
